# Generated by Django 3.0.6 on 2020-10-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_notification_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='like',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
    ]
