# Generated by Django 3.0.6 on 2020-10-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201019_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
    ]
