# Generated by Django 3.0.6 on 2020-10-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_notification_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='like',
        ),
    ]
